### ISSUE TITLE
Issue while executing setup_local.sh

### ISSUE THREAD

**Issue by rbachu** [LexPredict/lexpredict-contraxsuite-deploy#1]
Hi,

Upon executing ./setup_local.sh | tee -a log.txt
the script is  repeatedly prompting to enter password for user 'ubuntu',
Even upon giving the password it is still not proceeding further.
I noticed this user -'ubuntu' is being configured in local/fabrirc. 
Tried even creating a new user and configuring it, but that also did not work.

Can you please tell me how this user - 'ubuntu' is being used and any pointers to how to overcome this issue?

Please find below the screen capture on the shell script execution
Reading package lists...
Building dependency tree...
Reading state information...
:
Requirement already satisfied: asn1crypto>=0.21.0 in ./ve/lib/python3.5/site-packages (from cryptography>=1.1->para
miko<3.0,>=2.0->Fabric3==1.13.1.post1)
Requirement already satisfied: pycparser in ./ve/lib/python3.5/site-packages (from cffi>=1.1->bcrypt>=3.1.3->parami
ko<3.0,>=2.0->Fabric3==1.13.1.post1)
[localhost] Login password for 'ubuntu': 
[localhost] Login password for 'ubuntu':

**Comment by mjbommar** [comment]
Hello rbachu,
  Thank you for your note.  Please email support@contraxsuite.com with your fabricrc file so we can assist further.

  Can you please also provide in the email information about:
  * what operating system/version you are using
  * are you running as root account?
  * does the ubuntu user account have sudo privileges?

**Comment by mjbommar** [comment]
@rbachu, @bhaveshp3:
1. Please update your copy of the `-deploy` repository 
2. Please review the updated README instructions, especially this section: "confirm passwordless ssh to localhost".

Please let us know if this clarifies the issue for your install.

**Comment by rbachu** [comment]
Hi @mjbommar,
Yes, the confirm passwordless ssh to localhost step helped to setup on the local machine.

I notice the application is not rendering the UI properly, (probably some css files are not getting deployed correctly). 
Can you please point me to the document/links that explains how to use the sample files and run analysis.

Thanks

**Comment by mjbommar** [comment]
Hello @rbachu , glad to hear this resolved the issue for you.

Regarding your rendering question, please see the Canvas UI and jqWidgets sections of the Software and Data Dependency document:
https://github.com/LexPredict/lexpredict-contraxsuite/blob/1.0/documentation/Software%20and%20Data%20Dependencies.pdf

The UI and Javascript library require separate licensing and unfortunately we cannot legally redistribute them.

**Comment by bhaveshp3** [comment]
Hi @mjbommar 

Thank you for updating ssh key based authentication for setup_local.sh. It worked
