### ISSUE TITLE
Tasks hang

### ISSUE THREAD

**Issue by dwmcqueen** [LexPredict/lexpredict-contraxsuite-deploy#11]
After a clean install with the script, I ran the admin task to Load Dictionary Data.  The tasks load on the page, but stays at 0%  I tried a basic connection to celery to see if all works  and no errors were returned.

There are no errors in celery.log or the rabbitmq logs.  There is a warning (shown in the attached).
[rabbit@localhost.log](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1617209/rabbit.localhost.log)

**Comment by dwmcqueen** [comment]
I have tried restarting celery and the celery log is empty.  Should these tasks run?

**Comment by dwmcqueen** [comment]
If it helps:

1. celery report yields:

(ve) root@localhost:/opt/lexpredict-contraxsuite/contraxsuite_services# celery report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

2.  /opt/lexpredict-contraxsuite/contraxsuite_services# celery inspect registered -A apps
/opt/ve/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator SelectKBest from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/ve/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LogisticRegressionCV from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/ve/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator Pipeline from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/ve/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/ve/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator ExtraTreesClassifier from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Error: No nodes replied within time constraint.

**Comment by reddalexx** [comment]
This log shows that celery is not started - "No nodes replied within time constraint."
Start celery: celery multi 2 -A apps -f celery.log -B

**Comment by dwmcqueen** [comment]
(ve) root@localhost:/opt/lexpredict-contraxsuite/contraxsuite_services# celery multi restart 2 -A apps -f celery.log -B
celery multi v4.1.0 (latentcall)
> Restarting node celery1@localhost: OK
> Restarting node celery2@localhost: OK
(ve) root@localhost:/opt/lexpredict-contraxsuite/contraxsuite_services# celery report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

**Comment by dwmcqueen** [comment]
Then same error (No nodes replied within time constraint)

**Comment by dwmcqueen** [comment]
I also just ran "celery multi start 2 -A apps -f celery.log -B" which indicated that two nodes started.  Same error on check.

**Comment by reddalexx** [comment]
Perhaps celery broker fails
you should be sure it's communicating with the same broker
perhaps rabbitmq was not installed or configured properly

please check this: "celery -b amqp://contrax1:contrax1@localhost:5672/contrax1_vhost status"
it points to broker directly

and this: "sudo rabbitmqctl status" and "sudo rabbitmqctl report"

**Comment by dwmcqueen** [comment]
(ve) root@localhost:/opt# celery -b amqp://contrax1:contrax1@localhost:5672/contrax1_vhost status
Error: No nodes replied within time constraint.

The results of the rabbitmqctl status and report are attached.
[rabbitmql.status.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1623133/rabbitmql.status.txt)
[rabbitmql.report.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1623134/rabbitmql.report.txt)

**Comment by dwmcqueen** [comment]
For clarity, aside from installing git, unzip and fabric, this is a clean, updated Ubuntu 16.04 LTS 64 bit install.  Nothing else was installed.

**Comment by dwmcqueen** [comment]
I believe the issue may stem from running celery as root.  I tried the C_FORCE_ROOT=true before the command and it may have solved the issue (but still checking).

**Comment by dwmcqueen** [comment]
That fixed it.  The fabfile.py (with the change) is attached.
[fabfile.py.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1624257/fabfile.py.txt)

**Comment by dwmcqueen** [comment]
#13 # - should solve this issue.

**Comment by reddalexx** [comment]
Yes, we don't use root for deployment, so perhaps there may be some bottlenecks during deploying.

Also note that celery documentation says that "Running the worker with superuser privileges is a very dangerous practice. There should always be a workaround to avoid running as root. Celery may run arbitrary code in messages serialized with pickle - this is dangerous, especially when run as root."

Anyway I added ability to start celery as root is a user has "celery_run_as_root = true" in fabricrc file.

Thank you for your help.

**Comment by dwmcqueen** [comment]
That makes sense as a fix. I'll note that running the script as a non-root user for some reason still had celery running as root.  I am not sure why that is.
