### ISSUE TITLE
WSGI denying connections on reboot

### ISSUE THREAD

**Issue by dwmcqueen** [LexPredict/lexpredict-contraxsuite-deploy#12]
I ran the deploy script and everything ran just fine.  On a reboot, I got the " We're sorry. It looks like something went wrong. Please contact your IT administrator or refer to the LexPredict resources below: "

It looks like a connection issue in the nginx logs I get this:

2018/01/10 02:23:57 [error] 3640#3640: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 65.28.96.94, server: li826-159.members.linode.com, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8001", host: "li826-159.members.linode.com"

I did a service status check on uwsgi and it says "active (exited)", so it appears to be running.

**Comment by dwmcqueen** [comment]
For posterity sake, I had to run the following and all is well:

sudo systemctl status uwsgi 
fab -c local/fabricrc start 

I have to do this on each reboot - not sure this can be baked into the script.

**Comment by dwmcqueen** [comment]
I also ran "sudo update-rc.d uwsgi enable" to get the uwsgi services to start on reboot

**Comment by reddalexx** [comment]
Hi,
 try to restart services:

*#1 variant*: 
cd to that directory where deployment scripts were installed (lexpredict-contraxsuite-deploy)
activate virtual environment and run command
`fab -c remote/fabricrc restart`

*#2 variant*:
ssh to remote machine
```
sudo systemctl restart contrax_uwsgi
sudo systemctl restart nginx
cd /opt
source ve/bin/activate
cd lexpredict-contraxsuite/contraxsuite_services
celery multi restart 2 -A apps -f celery.log -B
```
i.e. restart uwsgi, nginx, celery

**Comment by dwmcqueen** [comment]
I think that works.  Should I expect a reboot to bring it back up or is that a command to run on restart?

**Comment by dwmcqueen** [comment]
(in other words, I think this issue can be closed as long as it is expected that on each reboot the command is run).

**Comment by reddalexx** [comment]
Yes, we don't use root for deployment, so perhaps there may be some bottlenecks during deploying.

Also note that celery documentation says that "Running the worker with superuser privileges is a very dangerous practice. There should always be a workaround to avoid running as root. Celery may run arbitrary code in messages serialized with pickle - this is dangerous, especially when run as root."

Anyway I added ability to start cekery as roo, see [this](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/commit/e4acb95122b7e6f8259e07b63c28a4343e93d15a) commit.
