### ISSUE TITLE
Not able to login to UI of Suite Predict

### ISSUE THREAD

**Issue by bhaveshp3** [LexPredict/lexpredict-contraxsuite-deploy#2]
Hi

I am not able to login to UI of Suite Predict.
http://52.209.208.143/accounts/login/

I am entering username and password which is set as **superuser_username** and **superuser_password**
in the file lexpredict-contraxsuite-deploy/base/fabricrc but still it is not working.

Please let me know what should be username and password if i am wrong and how and which file/database should be updated to work properly.

Thank you

![ice_screenshot_20170825-171603](https://user-images.githubusercontent.com/16354213/29712895-bac0c9d4-89b9-11e7-8180-c574bbc8bfd7.png)

**Comment by mjbommar** [comment]
Hello @bhaveshp3 , please refer to the Software and Data Dependency documentation here:
https://github.com/LexPredict/lexpredict-contraxsuite/blob/1.0/documentation/Software%20and%20Data%20Dependencies.pdf

You need to obtain licenses for jQWidgets and the default ContraxSuite theme:
* http://www.jqwidgets.com/
* https://themeforest.net/item/canvas-the-multipurpose-html5-template/9228123

Until you have completed these steps, the web application will not function properly.  You can use the API or core internal methods even without the web application.
