### ISSUE TITLE
Errors due to corporate firewall 

### ISSUE THREAD

**Issue by emichaelsomm** [LexPredict/lexpredict-contraxsuite-deploy#8]
I'm getting an error while running the deployment script, and I believe it is due to our corporate firewall.  Our firm's security policy places strong restrictions on how our servers access the internet.  

I can make a request to our security team to allow the ContraxSuite server to access specific domains (they've permitted access to Github, for example).  Would you happen to have a list of domains that I can provide to our security team?  Alternatively, is there a way to run the deployment script successfully without the need for internet access? 

Attached is the log file.  Any help you can provide would be most appreciated. 

[log.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1458906/log.txt)

**Comment by mjbommar** [comment]
Hello @emichaelsomm , we'll review the log and get back to you this week.  There are a few options that could work.

**Comment by emichaelsomm** [comment]
Much appreciated!

**Comment by ericlex** [comment]
@emichaelsomm - Thanks for reaching out to us. Based on your feedback and log, it seems there was a failure to execute `apt-get update --fix-missing` and and `pip install` failed to install initial `ve` for fabric commands as well.

The best solution in this case would be to ask your network team to whitelist this server on the firewall / proxy to allow access to anything on the internet. If they are unable to do this, then the next best thing would be to allow access to the URLs below on the firewall / proxy using a wildcard - so *.launchpad.net for example. I'm happy to jump on a quick call to work through some deployment options for you as well if thats easier for you. 

1. Apt-get update: logs show at least failed java installation, url `http://ppa.launchpad.net/webupd8team/java`
2. Pip: at least to start with `pypi.python.org` and then add for failed packages
3. Redis / Rabbitmq: `http://download.redis.io/releases` / `www.rabbitmq.com`
4. Java: `http://ppa.launchpad.net/webupd8team/java/`
5. Elasticsearch: `https://artifacts.elastic.co`
6. Nltk libs: `http://nltk.org/` or `https://raw.githubusercontent.com/nltk` or `https://github.com/nltk/nltk_data/` - I'm not sure which works
7. Yuglify via npm: perhaps `https://github.com/yui/yuglify`, I'm not sure
8. Optionally for stanford: `https://nlp.stanford.edu/software/`

Here is a reference article as well. 
https://stackoverflow.com/questions/14277088/what-url-should-i-authorize-to-use-pip-behind-a-firewall

**Comment by ericlex** [comment]
@emichaelsomm - I was hoping to check in to make sure you are able to proceed with the install now. Is there anything else we can help on to get things working behind the firewall?

**Comment by emichaelsomm** [comment]
Hi @ericlex , I appreciate your quick response and follow-up.  I need to reach out to our network security team today in order to find out if they'd be willing to whitelist our ContraxSuite server per your first suggestion. If they deny that request, then we will need to explore the other options. 

I'll let you know as soon as I hear back from them.  Thanks again for your help!

**Comment by emichaelsomm** [comment]
Hi @ericlex, I was able to complete the installation by having our security team whitelist the appropriate URLs.  I'm now running version 1.0.3.  Thanks!!

**Comment by ericlex** [comment]
Good to hear @emichaelsomm - I'll follow-up next week to make sure things are going well. Also - please make sure to update to 1.0.4 when its released in the next couple days. We have been busy and have a lot more cool things coming soon!
